In [2]:
base_url = 'http://localhost:8000'
base_url = 'http://127.0.0.1:9123'

In [4]:
import requests 
import pandas as pd

url = f'{base_url}/predict_file'

with open("../api_dfs/X_test.csv", "rb") as file:
    files = {"file": ("data.csv", file, "text/csv")}
    response = requests.post(url, files=files)
print(response)
pd.read_json(response.json())

<Response [200]>

/tmp/ipykernel_20012/15442267.py:10: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(response.json())

     0
0    0
1    0
2    0
3    0
4    0
..  ..
367  0
368  0
369  0
370  0
371  0

[372 rows x 1 columns]

In [5]:
url = f'{base_url}/predict_str'

X_test = pd.read_csv('../api_dfs/X_test.csv')
payload = {"data": X_test.to_json(orient='records')}
response = requests.post(url, json=payload)
print(response)
pd.read_json(response.json())

<Response [200]>

/tmp/ipykernel_20012/3614576630.py:7: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(response.json())

     0
0    0
1    0
2    0
3    0
4    0
..  ..
367  0
368  0
369  0
370  0
371  0

[372 rows x 1 columns]

In [6]:
url = f'{base_url}/predict_each_col'

X_test = pd.read_csv('../api_dfs/X_test.csv')
payload = {"data": X_test.to_dict(orient='records')}
response = requests.post(url, json=payload)
print(response)
pd.read_json(response.json())

<Response [200]>

/tmp/ipykernel_20012/1744728329.py:7: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(response.json())

     0
0    0
1    0
2    0
3    0
4    0
..  ..
367  0
368  0
369  0
370  0
371  0

[372 rows x 1 columns]

In [9]:
y_test = pd.read_csv('y_test.csv')

In [11]:
y_pred = pd.read_json(response.json())

/tmp/ipykernel_20012/47806079.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  y_pred = pd.read_json(response.json())

In [13]:
from sklearn.metrics import fbeta_score
fbeta_score = fbeta_score(y_pred, y_test, beta=1.5)
fbeta_score

0.11304347826086956

In [25]:
payload

{'data': [{'id': 0.6444862477464297},
  {'id': 0.6465095974318239},
  {'id': -1.5712152731624902},
  {'id': 0.6325110197966118},
  {'id': 0.6417080312160433},
  {'id': 0.6434978436038026},
  {'id': 0.6353817122754748},
  {'id': 0.6336331149001609},
  {'id': 0.6462994722081915},
  {'id': 0.6436503422897983},
  {'id': -1.570377307738437},
  {'id': -1.5707850035341155},
  {'id': 0.6381048212376731},
  {'id': 0.6298411482286943},
  {'id': 0.6283213314670409},
  {'id': -1.5716481803324542},
  {'id': 0.6345818355737881},
  {'id': 0.6312680138828669},
  {'id': -1.5709839220127264},
  {'id': 0.6451797055099989},
  {'id': 0.6311033038845512},
  {'id': 0.6360583130225528},
  {'id': 0.626281304567862},
  {'id': -1.572041852242036},
  {'id': 0.6258992577075115},
  {'id': 0.6281804266627169},
  {'id': 0.6340733797879765},
  {'id': -1.5724149199829252},
  {'id': 0.6262409313951649},
  {'id': 0.6319900801241001},
  {'id': 0.6427255630516167},
  {'id': 0.627653322516473},
  {'id': -1.5712778804982734},
  {'id': -1.5724737674275169},
  {'id': -1.5701840022598297},
  {'id': 0.6441593858018712},
  {'id': 0.6381117407550003},
  {'id': -1.570712132414012},
  {'id': 0.6356246788361235},
  {'id': 0.646175584297141},
  {'id': 0.6361383296313022},
  {'id': -1.5710656758439017},
  {'id': -1.5710386875665003},
  {'id': 0.6241698092832868},
  {'id': 0.6434641760752401},
  {'id': -1.572767936475864},
  {'id': -1.5720818885937384},
  {'id': 0.6452470782544412},
  {'id': -1.5713001454673483},
  {'id': 0.6426790343536605},
  {'id': 0.6375611933191857},
  {'id': 0.624587071509001},
  {'id': 0.6384241236785718},
  {'id': -1.571559419029473},
  {'id': -1.572776302289309},
  {'id': 0.6369218116539921},
  {'id': 0.6427552625863411},
  {'id': 0.6318203990840804},
  {'id': 0.6347822790333838},
  {'id': 0.6359763228462938},
  {'id': 0.6438612781799468},
  {'id': 0.6278050404417753},
  {'id': 0.6335748782863685},
  {'id': 0.6462013525745787},
  {'id': -1.5709118560871822},
  {'id': 0.6342441720948152},
  {'id': 0.6289569612471522},
  {'id': -1.5712435649796297},
  {'id': 0.6353106037291528},
  {'id': 0.6361215358501092},
  {'id': -1.5721457330652897},
  {'id': -1.5727263674774326},
  {'id': 0.6269529555287977},
  {'id': -1.5726766908555774},
  {'id': -1.571366674562635},
  {'id': 0.6280769691985091},
  {'id': 0.6463757896272436},
  {'id': 0.633999339818149},
  {'id': 0.6457286378947992},
  {'id': 0.633302463981992},
  {'id': 0.6333853701365358},
  {'id': 0.6337920373551541},
  {'id': -1.572364176759049},
  {'id': -1.5713970559994974},
  {'id': -1.571033184985067},
  {'id': 0.6263216782702918},
  {'id': 0.6467564136532566},
  {'id': 0.6458574628371067},
  {'id': -1.5711013093892046},
  {'id': 0.6376738647011608},
  {'id': 0.6427295229731101},
  {'id': 0.6302118528280528},
  {'id': -1.5713399588512973},
  {'id': 0.6460933254610626},
  {'id': 0.6247130485906942},
  {'id': 0.6374544558008338},
  {'id': 0.6394652985769215},
  {'id': 0.631022431538475},
  {'id': 0.6346855115997692},
  {'id': 0.6327379717968495},
  {'id': 0.6264989349392955},
  {'id': 0.6241747294985031},
  {'id': -1.5720525811438455},
  {'id': 0.6314100463378313},
  {'id': 0.647727018265924},
  {'id': 0.6394771658395634},
  {'id': 0.6394296970623736},
  {'id': 0.6403881142038483},
  {'id': 0.6473819677073108},
  {'id': 0.6394455199071035},
  {'id': -1.5723746395560074},
  {'id': 0.6395424365985323},
  {'id': 0.6278868135933133},
  {'id': -1.5724771673631912},
  {'id': 0.6395819953050701},
  {'id': -1.5720287680110665},
  {'id': 0.6287243745107544},
  {'id': -1.5723929491049673},
  {'id': 0.6268199924554317},
  {'id': 0.6276444561157237},
  {'id': 0.6339410962905528},
  {'id': 0.6309741063933418},
  {'id': -1.5723796093342313},
  {'id': -1.5718712162387012},
  {'id': 0.6424087857505862},
  {'id': -1.5723134301555255},
  {'id': 0.6346864990072377},
  {'id': -1.5721043917636652},
  {'id': 0.6297573515083663},
  {'id': 0.6440137947721957},
  {'id': -1.5724444750455069},
  {'id': 0.6290910022596885},
  {'id': 0.6412033487499122},
  {'id': 0.6391725871878298},
  {'id': 0.6351081508679312},
  {'id': -1.5720070476918064},
  {'id': -1.5717709628637004},
  {'id': 0.6328642827532421},
  {'id': 0.6363981509435983},
  {'id': -1.5715900546287942},
  {'id': 0.6460259343074376},
  {'id': 0.6467702914543204},
  {'id': -1.571465409809258},
  {'id': 0.6373398159078777},
  {'id': 0.6277951884014481},
  {'id': 0.6325761434443996},
  {'id': -1.5718871822695812},
  {'id': 0.6447834249152143},
  {'id': -1.5713669364767426},
  {'id': 0.6267500660328975},
  {'id': 0.6352029564081917},
  {'id': 0.6374890462592946},
  {'id': -1.5725668678767122},
  {'id': -1.5712058423236892},
  {'id': -1.5717039454248338},
  {'id': 0.6468188642475132},
  {'id': 0.6274316701584343},
  {'id': 0.6329402691801329},
  {'id': -1.5707320547058716},
  {'id': 0.6370947379948376},
  {'id': 0.6307551733920019},
  {'id': 0.6313991964055331},
  {'id': 0.6427384328149992},
  {'id': 0.6307472842048005},
  {'id': 0.6417733490827469},
  {'id': 0.6452312257121263},
  {'id': 0.6275518530118416},
  {'id': 0.6348178270159712},
  {'id': 0.6405157277530943},
  {'id': 0.6446903063339974},
  {'id': 0.6424988659956435},
  {'id': -1.572599293451271},
  {'id': 0.646142878715202},
  {'id': 0.6324103768643181},
  {'id': 0.6384379641589971},
  {'id': -1.5722516926172485},
  {'id': 0.6290003268187315},
  {'id': -1.572481613410024},
  {'id': 0.6301931193447748},
  {'id': 0.6427423927529625},
  {'id': 0.6288239115995524},
  {'id': 0.6241953944883875},
  {'id': 0.634163217337252},
  {'id': -1.5704976727366713},
  {'id': 0.6437572939024961},
  {'id': -1.5716811686261845},
  {'id': -1.5712144872637082},
  {'id': 0.6245467205662277},
  {'id': 0.63345149926213},
  {'id': 0.6252809937212308},
  {'id': 0.6455027117031065},
  {'id': -1.5721153814424051},
  {'id': -1.570536741393229},
  {'id': 0.6261385237721622},
  {'id': 0.6279281936060498},
  {'id': -1.5720031222668736},
  {'id': 0.6304613148038377},
  {'id': 0.6306033100858875},
  {'id': 0.635063711773403},
  {'id': 0.6327014609998705},
  {'id': 0.6420633374774791},
  {'id': 0.637997076467341},
  {'id': 0.6417951220114803},
  {'id': 0.645667200193816},
  {'id': 0.6448636676409663},
  {'id': -1.5716191180343388},
  {'id': 0.6244660202690256},
  {'id': 0.6334850578681336},
  {'id': 0.6261946506049729},
  {'id': -1.5719848033499155},
  {'id': -1.5712113436604866},
  {'id': 0.6299229754609759},
  {'id': -1.5707260256460736},
  {'id': 0.6323403234289029},
  {'id': -1.5716557730026608},
  {'id': 0.644285174041278},
  {'id': -1.5722396584467784},
  {'id': 0.6323038173398445},
  {'id': -1.5712587583003854},
  {'id': 0.6397333120294033},
  {'id': 0.6266417324594838},
  {'id': 0.6324320838855997},
  {'id': -1.5719070739058625},
  {'id': -1.571454934526966},
  {'id': -1.5723657461877525},
  {'id': 0.6380988902351558},
  {'id': 0.6393100394215957},
  {'id': 0.6454928030368412},
  {'id': -1.5721195679450075},
  {'id': 0.6319180631931655},
  {'id': 0.6250811674451989},
  {'id': 0.6452530229787292},
  {'id': 0.6359545908754803},
  {'id': -1.5727255831348967},
  {'id': 0.6405958598828956},
  {'id': -1.572326247915642},
  {'id': 0.6328524408813088},
  {'id': 0.6337219525304559},
  {'id': 0.6452708572200581},
  {'id': 0.6372093687914779},
  {'id': 0.6273479389765368},
  {'id': 0.6309652304286444},
  {'id': -1.570822746991999},
  {'id': 0.6444099768727807},
  {'id': 0.636701468118456},
  {'id': 0.6372834857953819},
  {'id': 0.6357224634587689},
  {'id': 0.6405661810741692},
  {'id': 0.6420583886420723},
  {'id': 0.6414358882835706},
  {'id': -1.5715827231443735},
  {'id': -1.571042093906557},
  {'id': 0.6335985676237333},
  {'id': 0.629097901587308},
  {'id': 0.6460120598401456},
  {'id': 0.6436325173802854},
  {'id': 0.6401477401950398},
  {'id': 0.6377806098014157},
  {'id': 0.6462370320817948},
  {'id': -1.5710934491913349},
  {'id': 0.646209281318449},
  {'id': 0.6277932179971659},
  {'id': -1.5718285512699044},
  {'id': -1.5710711781911193},
  {'id': 0.6402951278030148},
  {'id': 0.6363378862582711},
  {'id': 0.6352602361666599},
  {'id': 0.6354014649401829},
  {'id': 0.6440940175538358},
  {'id': 0.6391478662116375},
  {'id': -1.5727987849575429},
  {'id': 0.6389095661417611},
  {'id': 0.6459179133107131},
  {'id': 0.624462083723334},
  {'id': 0.6321489179320526},
  {'id': 0.6292615187426561},
  {'id': -1.57091369057694},
  {'id': 0.635915078593198},
  {'id': 0.6332827247498315},
  {'id': -1.5717534237123687},
  {'id': 0.62519141481972},
  {'id': 0.63870984330842},
  {'id': 0.6330567195452622},
  {'id': 0.6269903832077057},
  {'id': 0.630046213345825},
  {'id': 0.6450558623766345},
  {'id': 0.6265107524136105},
  {'id': -1.572760616313707},
  {'id': 0.6434453620276094},
  {'id': 0.6256206297343527},
  {'id': 0.6356819664210928},
  {'id': -1.5727114648311122},
  {'id': 0.6341345875045966},
  {'id': 0.6328011266283654},
  {'id': 0.6412815196636128},
  {'id': -1.5709401591528065},
  {'id': 0.6387019337589647},
  {'id': -1.5704698777108752},
  {'id': 0.6322890176971386},
  {'id': 0.6289451343790565},
  {'id': 0.6412785511118128},
  {'id': 0.6329708616468372},
  {'id': -1.57105100272407},
  {'id': 0.6281794413371378},
  {'id': 0.642341474752042},
  {'id': 0.6248606845505991},
  {'id': 0.6310362388619734},
  {'id': 0.6245949449254214},
  {'id': 0.6472203624080255},
  {'id': 0.6306338793705779},
  {'id': -1.571372436652246},
  {'id': 0.6251589308076713},
  {'id': 0.6446972405999271},
  {'id': 0.627531165465049},
  {'id': 0.6264703762303924},
  {'id': 0.6316882121875174},
  {'id': -1.5714635766452405},
  {'id': -1.5714423639983468},
  {'id': -1.571105239457785},
  {'id': 0.6458971023587776},
  {'id': -1.5706780536046412},
  {'id': 0.6450667603736404},
  {'id': -1.5719973649404075},
  {'id': -1.5718921552273055},
  {'id': -1.5721368370251765},
  {'id': 0.6332590378379854},
  {'id': -1.5720667116621485},
  {'id': -1.5712697601714072},
  {'id': 0.6255979861668337},
  {'id': 0.6443792709476269},
  {'id': -1.5713522691482218},
  {'id': 0.6274021177165174},
  {'id': 0.6473542066883521},
  {'id': -1.5717238418416994},
  {'id': -1.5716877137529195},
  {'id': -1.571994486260869},
  {'id': 0.6256403199285437},
  {'id': 0.6348642374984033},
  {'id': 0.6292122355522548},
  {'id': 0.6308685826898645},
  {'id': -1.5709954519295124},
  {'id': 0.6428572331583305},
  {'id': 0.6458525079325632},
  {'id': 0.6314633101957694},
  {'id': 0.644858714326074},
  {'id': -1.571724103633198},
  {'id': 0.6416427147285599},
  {'id': -1.5714156509372836},
  {'id': 0.6248951339610171},
  {'id': 0.6318835351242797},
  {'id': 0.6360968392790058},
  {'id': 0.6245978974617761},
  {'id': 0.6320976153851241},
  {'id': 0.6284592864731544},
  {'id': 0.6401596100778179},
  {'id': 0.6292329343961792},
  {'id': 0.6265186307550318},
  {'id': -1.5703592120140006},
  {'id': 0.6435216091385736},
  {'id': 0.6292319487337902},
  {'id': 0.6454779400968803},
  {'id': 0.6447259684384938},
  {'id': -1.5720973268865155},
  {'id': 0.6319555512486562},
  {'id': 0.6460437729995497},
  {'id': -1.5704331657494746},
  {'id': 0.6288682608434372},
  {'id': -1.5710339710705574},
  {'id': -1.5709991205028788},
  {'id': -1.5725315642703896},
  {'id': 0.645144038179825},
  {'id': 0.6370067913886546}]}

In [17]:
X_test.dtypes

id                      float64
fea_1                   float64
fea_2                   float64
fea_3                   float64
fea_4                   float64
fea_5                   float64
fea_6                   float64
fea_7                   float64
fea_8                   float64
fea_9                   float64
fea_10                  float64
fea_11                  float64
OVD_t1_mean             float64
OVD_t1_max              float64
OVD_t2_mean             float64
OVD_t2_max              float64
OVD_t3_mean             float64
OVD_t3_max              float64
pay_normal_mean         float64
pay_normal_max          float64
prod_code_median        float64
update_date_mean        float64
report_date_mean        float64
prod_limit_mean         float64
new_balance_mean        float64
highest_balance_mean    float64
dtype: object

In [27]:
X_test = pd.read_csv('../api_dfs/X_test.csv')

In [28]:
import re
pattern = r'\D'
for i, j in dict(X_test.dtypes).items():
    nonum = ''.join(re.findall(pattern, str(j)))
    print(f"{i}: {nonum}")

id: float
fea_1: float
fea_2: float
fea_3: float
fea_4: float
fea_5: float
fea_6: float
fea_7: float
fea_8: float
fea_9: float
fea_10: float
fea_11: float
OVD_t1_mean: float
OVD_t1_max: float
OVD_t2_mean: float
OVD_t2_max: float
OVD_t3_mean: float
OVD_t3_max: float
pay_normal_mean: float
pay_normal_max: float
prod_code_median: float
update_date_mean: float
report_date_mean: float
prod_limit_mean: float
new_balance_mean: float
highest_balance_mean: float

In [7]:
X_test.to_json(orient='records')

'[{"id":0.6444862477,"fea_1":-1.0706542465,"fea_2":0.7104340576,"fea_3":0.79992322,"fea_4":-0.2071186525,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-0.0131282787,"fea_8":0.9366244353,"fea_9":-0.3520297847,"fea_10":0.6480614321,"fea_11":-1.2956658751,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-1.3623289157,"pay_normal_max":-1.6592678458,"prod_code_median":1.2958318303,"update_date_mean":1.6632537214,"report_date_mean":1.6632537214,"prod_limit_mean":-1.8095895717,"new_balance_mean":-0.3995681629,"highest_balance_mean":-1.1399591194},{"id":0.6465095974,"fea_1":-1.0706542465,"fea_2":-1.0256284826,"fea_3":-1.4301266199,"fea_4":-0.7143962156,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-0.0131282787,"fea_8":-1.7132358011,"fea_9":-0.3520297847,"fea_10":-0.5265325502,"fea_11":-1.2956658751,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":0.2416387034,"pay_normal_max":0.3750300381,"prod_code_median":-0.4850085003,"update_date_mean":0.412334745,"report_date_mean":0.412334745,"prod_limit_mean":-0.964374864,"new_balance_mean":-0.4152605289,"highest_balance_mean":-1.1589642278},{"id":-1.5712152732,"fea_1":1.1012601412,"fea_2":0.9908942893,"fea_3":-1.4301266199,"fea_4":0.2530956449,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-1.8533705449,"fea_8":-1.2589621187,"fea_9":-1.347391227,"fea_10":1.315597917,"fea_11":0.4516214624,"OVD_t1_mean":1.002310895,"OVD_t1_max":1.2982775282,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-0.0752124676,"pay_normal_max":0.9568946399,"prod_code_median":-1.4172242163,"update_date_mean":-0.4509122598,"report_date_mean":-0.4509122598,"prod_limit_mean":-0.3182345805,"new_balance_mean":-0.3836680514,"highest_balance_mean":-0.5087221559},{"id":0.6325110198,"fea_1":1.1012601412,"fea_2":-0.7508299882,"fea_3":0.79992322,"fea_4":0.465663172,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":-0.4529829429,"fea_9":1.0185622338,"fea_10":1.4549975939,"fea_11":1.0208634781,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":1.4292124892,"pay_normal_max":0.9568946399,"prod_code_median":0.511497295,"update_date_mean":-1.7129556261,"report_date_mean":-1.7129556261,"prod_limit_mean":2.0489876993,"new_balance_mean":0.0680653862,"highest_balance_mean":0.4413371408},{"id":0.6417080312,"fea_1":-1.0706542465,"fea_2":-0.9838818063,"fea_3":-0.6344111813,"fea_4":-1.4529290081,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":1.5077178476,"fea_8":1.354062268,"fea_9":-0.3520297847,"fea_10":-0.9488403264,"fea_11":0.6171705951,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-0.6486936935,"pay_normal_max":-1.4374120199,"prod_code_median":0.511497295,"update_date_mean":0.9543239784,"report_date_mean":0.9543239784,"prod_limit_mean":-0.8402473279,"new_balance_mean":-0.2135644173,"highest_balance_mean":-0.5919784565},{"id":0.6434978436,"fea_1":-1.0706542465,"fea_2":0.1799254532,"fea_3":-1.4301266199,"fea_4":0.2066318569,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-0.0131282787,"fea_8":-1.0319007033,"fea_9":-1.347391227,"fea_10":1.2962026142,"fea_11":-1.2956658751,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-1.1970084546,"pay_normal_max":-1.1493382023,"prod_code_median":-0.4850085003,"update_date_mean":1.2594393334,"report_date_mean":1.2594393334,"prod_limit_mean":-0.9013530191,"new_balance_mean":-0.3913503914,"highest_balance_mean":-1.1799302664},{"id":0.6353817123,"fea_1":1.1012601412,"fea_2":1.7013625324,"fea_3":0.79992322,"fea_4":2.1845235356,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":1.0712661468,"fea_9":1.0185622338,"fea_10":1.5080169656,"fea_11":1.465992794,"OVD_t1_mean":1.1104527022,"OVD_t1_max":1.2982775282,"OVD_t2_mean":1.4669167146,"OVD_t2_max":1.8636692626,"OVD_t3_mean":2.8508280538,"OVD_t3_max":2.5938849756,"pay_normal_mean":-0.1258187066,"pay_normal_max":0.9568946399,"prod_code_median":-1.4172242163,"update_date_mean":-1.4747242131,"report_date_mean":-1.4747242131,"prod_limit_mean":2.573697025,"new_balance_mean":1.1505683234,"highest_balance_mean":1.7497676224},{"id":0.6336331149,"fea_1":1.1012601412,"fea_2":0.390287796,"fea_3":-1.4301266199,"fea_4":-0.6313147872,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-1.8533705449,"fea_8":1.2103763758,"fea_9":-0.3520297847,"fea_10":-0.5265622772,"fea_11":-1.2956658751,"OVD_t1_mean":1.0761154997,"OVD_t1_max":0.8753213294,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":1.0038865524,"pay_normal_max":-0.0188297025,"prod_code_median":0.511497295,"update_date_mean":0.003104586,"report_date_mean":0.003104586,"prod_limit_mean":-0.374911027,"new_balance_mean":-0.3355164018,"highest_balance_mean":-0.011649983},{"id":0.6462994722,"fea_1":-1.0706542465,"fea_2":-0.0358032537,"fea_3":-1.4301266199,"fea_4":0.22228196,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-1.8533705449,"fea_8":-0.2785838897,"fea_9":-1.347391227,"fea_10":1.3162771531,"fea_11":0.7497834206,"OVD_t1_mean":0.5003106584,"OVD_t1_max":1.2982775282,"OVD_t2_mean":1.6226302244,"OVD_t2_max":2.0271650837,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-0.3618469331,"pay_normal_max":0.9568946399,"prod_code_median":-1.4172242163,"update_date_mean":-1.2000655842,"report_date_mean":-1.2000655842,"prod_limit_mean":-0.037861954,"new_balance_mean":-0.5138340655,"highest_balance_mean":0.0831039624},{"id":0.6436503423,"fea_1":-1.0706542465,"fea_2":-0.0358032537,"fea_3":0.79992322,"fea_4":-0.1663461611,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-0.0131282787,"fea_8":1.354062268,"fea_9":-0.3520297847,"fea_10":-0.5265622772,"fea_11":0.5350679452,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-0.8389492735,"pay_normal_max":-1.3715833757,"prod_code_median":0.511497295,"update_date_mean":1.0531526282,"report_date_mean":1.0531526282,"prod_limit_mean":-0.4072917158,"new_balance_mean":-0.0050449744,"highest_balance_mean":0.1263974865},{"id":-1.5703773077,"fea_1":-1.0706542465,"fea_2":1.2350829684,"fea_3":-1.4301266199,"fea_4":0.4390470536,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-1.8533705449,"fea_8":0.4406552945,"fea_9":1.0185622338,"fea_10":1.3465728284,"fea_11":-1.2956658751,"OVD_t1_mean":0.8772315811,"OVD_t1_max":0.8753213294,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-1.1224960584,"pay_normal_max":-1.4991026756,"prod_code_median":0.511497295,"update_date_mean":-0.4675355108,"report_date_mean":-0.4675355108,"prod_limit_mean":-0.4401660935,"new_balance_mean":-0.4561762197,"highest_balance_mean":-0.0730025521},{"id":-1.5707850035,"fea_1":-1.0706542465,"fea_2":-1.0605615573,"fea_3":0.79992322,"fea_4":-0.2920199713,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-0.0131282787,"fea_8":-1.2589621187,"fea_9":1.0185622338,"fea_10":-0.5265622772,"fea_11":-1.2956658751,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":0.2673645426,"pay_normal_max":-0.1419958463,"prod_code_median":-1.4172242163,"update_date_mean":0.5855727712,"report_date_mean":0.5855727712,"prod_limit_mean":-0.4484638714,"new_balance_mean":0.1455641868,"highest_balance_mean":0.2596331402},{"id":0.6381048212,"fea_1":1.1012601412,"fea_2":0.963287852,"fea_3":-1.4301266199,"fea_4":1.0854997005,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":1.5077178476,"fea_8":-1.3100234688,"fea_9":1.0185622338,"fea_10":-0.9480485033,"fea_11":-1.2956658751,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":0.6310803267,"pay_normal_max":-1.0670242843,"prod_code_median":0.511497295,"update_date_mean":0.169447767,"report_date_mean":0.169447767,"prod_limit_mean":0.601782123,"new_balance_mean":-0.2802940041,"highest_balance_mean":-0.2350781354},{"id":0.6298411482,"fea_1":-0.3493341442,"fea_2":-2.1337330164,"fea_3":0.79992322,"fea_4":0.04040146,"fea_5":0.2969011435,"fea_6":1.4725683218,"fea_7":-0.0131282787,"fea_8":1.2103763758,"fea_9":-0.3520297847,"fea_10":1.4550244096,"fea_11":0.710381167,"OVD_t1_mean":0.5628369118,"OVD_t1_max":0.8753213294,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":1.3087093624,"pay_normal_max":0.9568946399,"prod_code_median":0.511497295,"update_date_mean":0.3512855989,"report_date_mean":0.3512855989,"prod_limit_mean":-0.2409166635,"new_balance_mean":-0.233374493,"highest_balance_mean":-0.5793088018},{"id":0.6283213315,"fea_1":-0.3493341442,"fea_2":-0.8187608813,"fea_3":0.79992322,"fea_4":-1.1694037694,"fea_5":0.2969011435,"fea_6":1.4725683218,"fea_7":-0.0131282787,"fea_8":1.0712661468,"fea_9":-0.3520297847,"fea_10":0.6502477741,"fea_11":-1.2956658751,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-0.9377329621,"pay_normal_max":-0.9806038596,"prod_code_median":-0.7244936341,"update_date_mean":1.240692026,"report_date_mean":1.240692026,"prod_limit_mean":-0.4072917158,"new_balance_mean":-0.044955746,"highest_balance_mean":-0.1180747714},{"id":-1.5716481803,"fea_1":1.1012601412,"fea_2":0.0139886712,"fea_3":-0.6344111813,"fea_4":-0.4769749942,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":-1.40578002,"fea_9":-1.347391227,"fea_10":-0.9488403264,"fea_11":0.613245325,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":0.1140214902,"pay_normal_max":0.5144256535,"prod_code_median":-1.4172242163,"update_date_mean":0.0137235503,"report_date_mean":0.0137235503,"prod_limit_mean":-0.289100274,"new_balance_mean":-0.2639088642,"highest_balance_mean":0.2190261182},{"id":0.6345818356,"fea_1":1.1012601412,"fea_2":-0.2060042271,"fea_3":-0.6344111813,"fea_4":-0.9923229967,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":0.9366244353,"fea_9":-0.3520297847,"fea_10":-0.5265325502,"fea_11":0.6488017924,"OVD_t1_mean":1.9547819819,"OVD_t1_max":1.7792641581,"OVD_t2_mean":2.3010693846,"OVD_t2_max":2.0753106708,"OVD_t3_mean":2.6945153092,"OVD_t3_max":2.5558350123,"pay_normal_mean":-0.1258187066,"pay_normal_max":0.9568946399,"prod_code_median":-1.8555156259,"update_date_mean":0.1440221883,"report_date_mean":0.1440221883,"prod_limit_mean":-1.8095895717,"new_balance_mean":0.0576073929,"highest_balance_mean":0.7048154528},{"id":0.6312680139,"fea_1":1.1012601412,"fea_2":-0.1299461791,"fea_3":0.79992322,"fea_4":0.3128611149,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":-1.4506067029,"fea_9":1.0185622338,"fea_10":-0.9460085767,"fea_11":0.7308763036,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":0.8281510603,"pay_normal_max":0.8053610227,"prod_code_median":0.511497295,"update_date_mean":-1.5318005915,"report_date_mean":-1.5318005915,"prod_limit_mean":0.2021391449,"new_balance_mean":-0.5472492013,"highest_balance_mean":-1.6261831708},{"id":-1.570983922,"fea_1":-1.0706542465,"fea_2":0.5081532028,"fea_3":-1.4301266199,"fea_4":1.5634823448,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-0.0131282787,"fea_8":-1.7132358011,"fea_9":1.0185622338,"fea_10":-0.5265622772,"fea_11":0.7694584272,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-0.1061618378,"pay_normal_max":0.9568946399,"prod_code_median":0.511497295,"update_date_mean":-1.026210077,"report_date_mean":-1.026210077,"prod_limit_mean":0.486341825,"new_balance_mean":0.6784735832,"highest_balance_mean":1.0930141866},{"id":0.6451797055,"fea_1":-1.0706542465,"fea_2":1.9726129485,"fea_3":-1.4301266199,"fea_4":-0.2489912502,"fea_5":0.2969011435,"fea_6":-1.0812607236,"fea_7":-0.0131282787,"fea_8":0.2168119824,"fea_9":-0.3520297847,"fea_10":-0.9485068705,"fea_11":0.8324141858,"OVD_t1_mean":1.0761154997,"OVD_t1_max":0.8753213294,"OVD_t2_mean":2.0901621765,"OVD_t2_max":2.0271650837,"OVD_t3_mean":2.8498902717,"OVD_t3_max":2.5930681869,"pay_normal_mean":-0.358383163,"pay_normal_max":0.8053610227,"prod_code_median":-1.8555156259,"update_date_mean":-1.3792745683,"report_date_mean":-1.3792745683,"prod_limit_mean":0.4983620734,"new_balance_mean":0.539517455,"highest_balance_mean":1.1918982333},{"id":0.6311033039,"fea_1":1.1012601412,"fea_2":-1.0256284826,"fea_3":0.79992322,"fea_4":0.0048351699,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":0.9366244353,"fea_9":-0.3520297847,"fea_10":-0.5265622772,"fea_11":0.7408096154,"OVD_t1_mean":1.9080889448,"OVD_t1_max":1.5761032127,"OVD_t2_mean":1.9626914764,"OVD_t2_max":1.8636692626,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":1.4389424065,"pay_normal_max":0.9568946399,"prod_code_median":0.511497295,"update_date_mean":-0.0672528186,"report_date_mean":-0.0672528186,"prod_limit_mean":-1.4100783324,"new_balance_mean":-0.3076323152,"highest_balance_mean":-0.4207166538},{"id":0.636058313,"fea_1":1.1012601412,"fea_2":0.3307215009,"fea_3":0.79992322,"fea_4":-0.5782042618,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":-0.2785838897,"fea_9":1.0185622338,"fea_10":1.3297368198,"fea_11":0.813812742,"OVD_t1_mean":1.0761154997,"OVD_t1_max":0.8753213294,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-0.695398314,"pay_normal_max":0.8053610227,"prod_code_median":0.511497295,"update_date_mean":0.4501502235,"report_date_mean":0.4501502235,"prod_limit_mean":-2.1836951547,"new_balance_mean":-0.196371168,"highest_balance_mean":-0.4125831808},{"id":0.6262813046,"fea_1":-0.3493341442,"fea_2":1.7264389236,"fea_3":0.79992322,"fea_4":-0.358863905,"fea_5":0.2969011435,"fea_6":1.4725683218,"fea_7":-0.0131282787,"fea_8":1.502432569,"fea_9":1.0185622338,"fea_10":0.6502477741,"fea_11":-1.2956658751,"OVD_t1_mean":0.5628369118,"OVD_t1_max":1.4792136444,"OVD_t2_mean":0.7145710196,"OVD_t2_max":1.8636692626,"OVD_t3_mean":1.9117068541,"OVD_t3_max":2.575086785,"pay_normal_mean":0.8010230632,"pay_normal_max":0.9568946399,"prod_code_median":-0.7244936341,"update_date_mean":-0.9695669108,"report_date_mean":-0.9695669108,"prod_limit_mean":-0.1032062746,"new_balance_mean":0.1364598556,"highest_balance_mean":0.7517946898},{"id":-1.5720418522,"fea_1":1.1012601412,"fea_2":0.7673160928,"fea_3":0.79992322,"fea_4":0.707761728,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":1.0712661468,"fea_9":1.0185622338,"fea_10":1.4549856748,"fea_11":1.2104355086,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":-0.575082034,"pay_normal_max":0.6578703528,"prod_code_median":0.511497295,"update_date_mean":0.8404641845,"report_date_mean":0.8404641845,"prod_limit_mean":2.8571032466,"new_balance_mean":2.4772790915,"highest_balance_mean":1.9794456371},{"id":0.6258992577,"fea_1":-0.3493341442,"fea_2":2.2573727135,"fea_3":-1.4301266199,"fea_4":0.707761728,"fea_5":0.2969011435,"fea_6":1.4725683218,"fea_7":1.5077178476,"fea_8":-0.2785838897,"fea_9":1.0185622338,"fea_10":-0.5566166282,"fea_11":1.1246397153,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":0.8632151092,"pay_normal_max":0.9568946399,"prod_code_median":-1.1907928974,"update_date_mean":-1.2866271519,"report_date_mean":-1.2866271519,"prod_limit_mean":2.3451233691,"new_balance_mean":1.3089454969,"highest_balance_mean":2.7218435602},{"id":0.6281804267,"fea_1":-0.3493341442,"fea_2":0.7956073769,"fea_3":0.79992322,"fea_4":-4.0827491489,"fea_5":0.2969011435,"fea_6":1.4725683218,"fea_7":-0.0131282787,"fea_8":1.354062268,"fea_9":-1.347391227,"fea_10":1.4550124918,"fea_11":0.5350679452,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":0.0749007043,"pay_normal_max":0.9568946399,"prod_code_median":0.511497295,"update_date_mean":0.7165832857,"report_date_mean":0.7165832857,"prod_limit_mean":0.5161083583,"new_balance_mean":0.9215411026,"highest_balance_mean":1.2529837867},{"id":0.6340733798,"fea_1":1.1012601412,"fea_2":1.8996266355,"fea_3":0.79992322,"fea_4":0.2530956449,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":-0.0131282787,"fea_8":-0.2785838897,"fea_9":1.0185622338,"fea_10":-0.9464246375,"fea_11":-1.2956658751,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":2.8510755126,"OVD_t3_max":2.5938988708,"pay_normal_mean":-1.8953982884,"pay_normal_max":-1.3715833757,"prod_code_median":-0.4850085003,"update_date_mean":-1.2722017472,"report_date_mean":-1.2722017472,"prod_limit_mean":0.4180499717,"new_balance_mean":0.0528521007,"highest_balance_mean":-0.1870222653},{"id":-1.57241492,"fea_1":-0.3493341442,"fea_2":-0.0984510629,"fea_3":0.79992322,"fea_4":-0.501688425,"fea_5":0.2969011435,"fea_6":1.4725683218,"fea_7":-0.0131282787,"fea_8":-1.09222922,"fea_9":1.0185622338,"fea_10":-0.9488403264,"fea_11":0.6065072972,"OVD_t1_mean":1.7691394024,"OVD_t1_max":1.5761032127,"OVD_t2_mean":2.2444608507,"OVD_t2_max":2.0271650837,"OVD_t3_mean":2.851086297,"OVD_t3_max":2.5939631504,"pay_normal_mean":-1.2512268532,"pay_normal_max":-0.0188297025,"prod_code_median":-1.8555156259,"update_date_mean":-1.802782597,"report_date_mean":-1.802782597,"prod_limit_mean":-1.5020019048,"new_balance_mean":-0.2741284167,"highest_balance_mean":0.167719819},{"id":0.6262409314,"fea_1":-0.3493341442,"fea_2":1.0622226688,"fea_3":0.79992322,"fea_4":0.7515933518,"fea_5":0.2969011435,"fea_6":1.4725683218,"fea_7":-0.0131282787,"fea_8":0.8063456856,"fea_9":1.0185622338,"fea_10":-0.9473404238,"fea_11":0.7694584272,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":-0.4884914534,"OVD_t2_max":-0.4984190282,"OVD_t3_mean":-0.3817067427,"OVD_t3_max":-0.3954451926,"pay_normal_mean":0.3718917169,"pay_normal_max":0.9568946399,"prod_code_median":0.511497295,"update_date_mean":-0.3326578006,"report_date_mean":-0.3326578006,"prod_limit_mean":1.0442817618,"new_balance_mean":-0.4253063629,"highest_balance_mean":-0.3341388995},{"id":0.6319900801,"fea_1":1.1012601412,"fea_2":0.5664602295,"fea_3":0.79992322,"fea_4":1.1353541403,"fea_5":0.2969011435,"fea_6":0.1323902908,"fea_7":1.5077178476,"fea_8":-0.6913064813,"fea_9":1.0185622338,"fea_10":-0.5264730985,"fea_11":0.7207366879,"OVD_t1_mean":-0.7187127528,"OVD_t1_max":-0.7627053267,"OVD_t2_mean":2.3013310028,"OVD

In [9]:
str(X_test.to_dict(orient='records'))

"[{'id': 0.6444862477464297, 'fea_1': -1.0706542464580389, 'fea_2': 0.7104340576214382, 'fea_3': 0.7999232200119571, 'fea_4': -0.2071186525484182, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -0.0131282786815867, 'fea_8': 0.9366244353457758, 'fea_9': -0.3520297846853395, 'fea_10': 0.6480614320565465, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -1.3623289157383829, 'pay_normal_max': -1.6592678458398415, 'prod_code_median': 1.2958318302891814, 'update_date_mean': 1.6632537213521097, 'report_date_mean': 1.6632537213521097, 'prod_limit_mean': -1.809589571733241, 'new_balance_mean': -0.3995681629150565, 'highest_balance_mean': -1.1399591194409366}, {'id': 0.6465095974318239, 'fea_1': -1.0706542464580389, 'fea_2': -1.02562848255036, 'fea_3': -1.4301266199062346, 'fea_4': -0.714396215566627, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -0.0131282786815867, 'fea_8': -1.71323580105938, 'fea_9': -0.3520297846853395, 'fea_10': -0.5265325501624377, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 0.2416387033680429, 'pay_normal_max': 0.3750300380867798, 'prod_code_median': -0.485008500281634, 'update_date_mean': 0.41233474497547, 'report_date_mean': 0.41233474497547, 'prod_limit_mean': -0.9643748640181936, 'new_balance_mean': -0.4152605288522923, 'highest_balance_mean': -1.1589642278473016}, {'id': -1.5712152731624902, 'fea_1': 1.1012601411532634, 'fea_2': 0.990894289298116, 'fea_3': -1.4301266199062346, 'fea_4': 0.2530956448540556, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -1.8533705449298423, 'fea_8': -1.2589621186541062, 'fea_9': -1.3473912269585822, 'fea_10': 1.3155979170313183, 'fea_11': 0.4516214623772975, 'OVD_t1_mean': 1.0023108950098187, 'OVD_t1_max': 1.298277528213185, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -0.0752124676198056, 'pay_normal_max': 0.9568946399352508, 'prod_code_median': -1.417224216255988, 'update_date_mean': -0.4509122597919255, 'report_date_mean': -0.4509122597919255, 'prod_limit_mean': -0.3182345804863329, 'new_balance_mean': -0.3836680513717901, 'highest_balance_mean': -0.5087221558639181}, {'id': 0.6325110197966118, 'fea_1': 1.1012601411532634, 'fea_2': -0.7508299882066574, 'fea_3': 0.7999232200119571, 'fea_4': 0.4656631720223532, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -0.0131282786815867, 'fea_8': -0.4529829429086784, 'fea_9': 1.0185622338373752, 'fea_10': 1.4549975938607247, 'fea_11': 1.0208634781474606, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 1.429212489161171, 'pay_normal_max': 0.9568946399352508, 'prod_code_median': 0.5114972949866168, 'update_date_mean': -1.7129556260661714, 'report_date_mean': -1.7129556260661714, 'prod_limit_mean': 2.048987699326514, 'new_balance_mean': 0.0680653861770341, 'highest_balance_mean': 0.4413371408003102}, {'id': 0.6417080312160433, 'fea_1': -1.0706542464580389, 'fea_2': -0.983881806283822, 'fea_3': -0.6344111813154315, 'fea_4': -1.4529290080544632, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': 1.507717847624837, 'fea_8': 1.3540622680498842, 'fea_9': -0.3520297846853395, 'fea_10': -0.9488403264360944, 'fea_11': 0.6171705951315757, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -0.6486936935435655, 'pay_normal_max': -1.4374120198948934, 'prod_code_median': 0.5114972949866168, 'update_date_mean': 0.9543239784055324, 'report_date_mean': 0.9543239784055324, 'prod_limit_mean': -0.8402473279243157, 'new_balance_mean': -0.2135644172506056, 'highest_balance_mean': -0.5919784564870293}, {'id': 0.6434978436038026, 'fea_1': -1.0706542464580389, 'fea_2': 0.1799254531502402, 'fea_3': -1.4301266199062346, 'fea_4': 0.206631856888789, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -0.0131282786815867, 'fea_8': -1.0319007032906655, 'fea_9': -1.3473912269585822, 'fea_10': 1.2962026142383416, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -1.1970084545671371, 'pay_normal_max': -1.1493382023305878, 'prod_code_median': -0.485008500281634, 'update_date_mean': 1.259439333367386, 'report_date_mean': 1.259439333367386, 'prod_limit_mean': -0.9013530191301644, 'new_balance_mean': -0.3913503914157901, 'highest_balance_mean': -1.1799302663688735}, {'id': 0.6353817122754748, 'fea_1': 1.1012601411532634, 'fea_2': 1.7013625323556043, 'fea_3': 0.7999232200119571, 'fea_4': 2.1845235355715555, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -0.0131282786815867, 'fea_8': 1.0712661468005773, 'fea_9': 1.0185622338373752, 'fea_10': 1.5080169656289968, 'fea_11': 1.4659927940281168, 'OVD_t1_mean': 1.1104527022002415, 'OVD_t1_max': 1.298277528213185, 'OVD_t2_mean': 1.4669167146381747, 'OVD_t2_max': 1.863669262634988, 'OVD_t3_mean': 2.850828053753039, 'OVD_t3_max': 2.593884975586303, 'pay_normal_mean': -0.1258187066416832, 'pay_normal_max': 0.9568946399352508, 'prod_code_median': -1.417224216255988, 'update_date_mean': -1.474724213117626, 'report_date_mean': -1.474724213117626, 'prod_limit_mean': 2.5736970250434354, 'new_balance_mean': 1.1505683233638764, 'highest_balance_mean': 1.7497676223676226}, {'id': 0.6336331149001609, 'fea_1': 1.1012601411532634, 'fea_2': 0.3902877959532019, 'fea_3': -1.4301266199062346, 'fea_4': -0.6313147871923263, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -1.8533705449298423, 'fea_8': 1.2103763757843302, 'fea_9': -0.3520297846853395, 'fea_10': -0.5265622771629388, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': 1.076115499686606, 'OVD_t1_max': 0.8753213294496587, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 1.003886552447638, 'pay_normal_max': -0.0188297025433763, 'prod_code_median': 0.5114972949866168, 'update_date_mean': 0.0031045859962663, 'report_date_mean': 0.0031045859962663, 'prod_limit_mean': -0.3749110269705504, 'new_balance_mean': -0.3355164018437868, 'highest_balance_mean': -0.0116499830276167}, {'id': 0.6462994722081915, 'fea_1': -1.0706542464580389, 'fea_2': -0.0358032537160507, 'fea_3': -1.4301266199062346, 'fea_4': 0.2222819600200567, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -1.8533705449298423, 'fea_8': -0.2785838896599469, 'fea_9': -1.3473912269585822, 'fea_10': 1.3162771531307886, 'fea_11': 0.7497834206345761, 'OVD_t1_mean': 0.5003106584048056, 'OVD_t1_max': 1.298277528213185, 'OVD_t2_mean': 1.622630224398408, 'OVD_t2_max': 2.027165083673914, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -0.3618469331440885, 'pay_normal_max': 0.9568946399352508, 'prod_code_median': -1.417224216255988, 'update_date_mean': -1.2000655842144838, 'report_date_mean': -1.2000655842144838, 'prod_limit_mean': -0.0378619540311526, 'new_balance_mean': -0.5138340654978877, 'highest_balance_mean': 0.0831039623758949}, {'id': 0.6436503422897983, 'fea_1': -1.0706542464580389, 'fea_2': -0.0358032537160507, 'fea_3': 0.7999232200119571, 'fea_4': -0.1663461611445217, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -0.0131282786815867, 'fea_8': 1.3540622680498842, 'fea_9': -0.3520297846853395, 'fea_10': -0.5265622771629388, 'fea_11': 0.5350679451806599, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -0.8389492735219501, 'pay_normal_max': -1.3715833757218885, 'prod_code_median': 0.5114972949866168, 'update_date_mean': 1.0531526282371817, 'report_date_mean': 1.0531526282371817, 'prod_limit_mean': -0.4072917158496471, 'new_balance_mean': -0.005044974438705, 'highest_balance_mean': 0.1263974865233779}, {'id': -1.570377307738437, 'fea_1': -1.0706542464580389, 'fea_2': 1.2350829684179965, 'fea_3': -1.4301266199062346, 'fea_4': 0.4390470535960411, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -1.8533705449298423, 'fea_8': 0.4406552944882673, 'fea_9': 1.0185622338373752, 'fea_10': 1.3465728283509524, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': 0.8772315810974748, 'OVD_t1_max': 0.8753213294496587, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -1.122496058408934, 'pay_normal_max': -1.4991026756248182, 'prod_code_median': 0.5114972949866168, 'update_date_mean': -0.4675355108372985, 'report_date_mean': -0.4675355108372985, 'prod_limit_mean': -0.4401660935093099, 'new_balance_mean': -0.4561762196748332, 'highest_balance_mean': -0.0730025520979768}, {'id': -1.5707850035341155, 'fea_1': -1.0706542464580389, 'fea_2': -1.0605615573252167, 'fea_3': 0.7999232200119571, 'fea_4': -0.2920199713177706, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -0.0131282786815867, 'fea_8': -1.2589621186541062, 'fea_9': 1.0185622338373752, 'fea_10': -0.5265622771629388, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 0.2673645425761169, 'pay_normal_max': -0.1419958463216693, 'prod_code_median': -1.417224216255988, 'update_date_mean': 0.5855727711744707, 'report_date_mean': 0.5855727711744707, 'prod_limit_mean': -0.448463871368405, 'new_balance_mean': 0.1455641868066541, 'highest_balance_mean': 0.2596331402039749}, {'id': 0.6381048212376731, 'fea_1': 1.1012601411532634, 'fea_2': 0.9632878519804552, 'fea_3': -1.4301266199062346, 'fea_4': 1.085499700490922, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': 1.507717847624837, 'fea_8': -1.310023468767434, 'fea_9': 1.0185622338373752, 'fea_10': -0.948048503266989, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 0.6310803266889449, 'pay_normal_max': -1.067024284335091, 'prod_code_median': 0.5114972949866168, 'update_date_mean': 0.1694477669713245, 'report_date_mean': 0.1694477669713245, 'prod_limit_mean': 0.6017821230058897, 'new_balance_mean': -0.2802940040766478, 'highest_balance_mean': -0.2350781353682071}, {'id': 0.6298411482286943, 'fea_1': -0.3493341442095938, 'fea_2': -2.133733016418157, 'fea_3': 0.7999232200119571, 'fea_4': 0.040401460032655, 'fea_5': 0.2969011435096554, 'fea_6': 1.472568321829104, 'fea_7': -0.0131282786815867, 'fea_8': 1.2103763757843302, 'fea_9': -0.3520297846853395, 'fea_10': 1.455024409554953, 'fea_11': 0.7103811670411262, 'OVD_t1_mean': 0.562836911752621, 'OVD_t1_max': 0.8753213294496587, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 1.3087093624078718, 'pay_normal_max': 0.9568946399352508, 'prod_code_median': 0.5114972949866168, 'update_date_mean': 0.3512855988598388, 'report_date_mean': 0.3512855988598388, 'prod_limit_mean': -0.2409166635067232, 'new_balance_mean': -0.2333744929783604, 'highest_balance_mean': -0.57930880180295}, {'id': 0.6283213314670409, 'fea_1': -0.3493341442095938, 'fea_2': -0.8187608812553541, 'fea_3': 0.7999232200119571, 'fea_4': -1.1694037694240562, 'fea_5': 0.2969011435096554, 'fea_6': 1.472568321829104, 'fea_7': -0.0131282786815867, 'fea_8': 1.0712661468005773, 'fea_9': -0.3520297846853395, 'fea_10': 0.650247774085827, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -0.9377329621064092, 'pay_normal_max': -0.9806038595592512, 'prod_code_median': -0.724493634129952, 'update_date_mean': 1.2406920260332432, 'report_date_mean': 1.2406920260332432, 'prod_limit_mean': -0.4072917158496471, 'new_balance_mean': -0.0449557460214382, 'highest_balance_mean': -0.1180747713756709}, {'id': -1.5716481803324542, 'fea_1': 1.1012601411532634, 'fea_2': 0.0139886711799746, 'fea_3': -0.6344111813154315, 'fea_4': -0.4769749942397657, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -0.0131282786815867, 'fea_8': -1.40578002001361, 'fea_9': -1.3473912269585822, 'fea_10': -0.9488403264360944, 'fea_11': 0.6132453249762295, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 0.1140214901591058, 'pay_normal_max': 0.5144256534591596, 'prod_code_median': -1.417224216255988, 'update_date_mean': 0.0137235502519422, 'report_date_mean': 0.0137235502519422, 'prod_limit_mean': -0.2891002740390602, 'new_balance_mean': -0.2639088641933674, 'highest_balance_mean': 0.2190261182004448}, {'id': 0.6345818355737881, 'fea_1': 1.1012601411532634, 'fea_2': -0.2060042270596887, 'fea_3': -0.6344111813154315, 'fea_4': -0.9923229966713274, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -0.0131282786815867, 'fea_8': 0.9366244353457758, 'fea_9': -0.3520297846853395, 'fea_10': -0.5265325501624377, 'fea_11': 0.6488017924200524, 'OVD_t1_mean': 1.9547819818578025, 'OVD_t1_max': 1.7792641580831146, 'OVD_t2_mean': 2.301069384611304, 'OVD_t2_max': 2.075310670842894, 'OVD_t3_mean': 2.694515309188336, 'OVD_t3_max': 2.555835012316241, 'pay_normal_mean': -0.1258187066416832, 'pay_normal_max': 0.9568946399352508, 'prod_code_median': -1.8555156258909091, 'update_date_mean': 0.1440221882726486, 'report_date_mean': 0.1440221882726486, 'prod_limit_mean': -1.809589571733241, 'new_balance_mean': 0.057607392863652, 'highest_balance_mean': 0.7048154527771765}, {'id': 0.6312680138828669, 'fea_1': 1.1012601411532634, 'fea_2': -0.1299461791121258, 'fea_3': 0.7999232200119571, 'fea_4': 0.3128611148822918, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -0.0131282786815867, 'fea_8': -1.4506067028734582, 'fea_9': 1.0185622338373752, 'fea_10': -0.9460085766702696, 'fea_11': 0.7308763036375739, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 0.8281510602698557, 'pay_normal_max': 0.8053610226981562, 'prod_code_median': 0.5114972949866168, 'update_date_mean': -1.531800591548736, 'report_date_mean': -1.531800591548736, 'prod_limit_mean': 0.2021391448819389, 'new_balance_mean': -0.5472492013381223, 'highest_balance_mean': -1.6261831707631424}, {'id': -1.5709839220127264, 'fea_1': -1.0706542464580389, 'fea_2': 0.5081532027857204, 'fea_3': -1.4301266199062346, 'fea_4': 1.563482344816956, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -0.0131282786815867, 'fea_8': -1.71323580105938, 'fea_9': 1.0185622338373752, 'fea_10': -0.5265622771629388, 'fea_11': 0.7694584272116276, 'OVD_t1_mean': -0.7187127527647533, 'OVD_t1_max': -0.7627053266837721, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -0.1061618378242755, 'pay_normal_max': 0.9568946399352508, 'prod_code_median': 0.5114972949866168, 'update_date_mean': -1.02621007698295, 'report_date_mean': -1.02621007698295, 'prod_limit_mean': 0.4863418249588391, 'new_balance_mean': 0.6784735832264805, 'highest_balance_mean': 1.0930141865640626}, {'id': 0.6451797055099989, 'fea_1': -1.0706542464580389, 'fea_2': 1.9726129485096648, 'fea_3': -1.4301266199062346, 'fea_4': -0.2489912502390888, 'fea_5': 0.2969011435096554, 'fea_6': -1.0812607236257736, 'fea_7': -0.0131282786815867, 'fea_8': 0.2168119824104037, 'fea_9': -0.3520297846853395, 'fea_10': -0.948506870535802, 'fea_11': 0.8324141857635537, 'OVD_t1_mean': 1.076115499686606, 'OVD_t1_max': 0.8753213294496587, 'OVD_t2_mean': 2.09016217649455, 'OVD_t2_max': 2.027165083673914, 'OVD_t3_mean': 2.849890271692351, 'OVD_t3_max': 2.5930681869263603, 'pay_normal_mean': -0.3583831629643155, 'pay_normal_max': 0.8053610226981562, 'prod_code_median': -1.8555156258909091, 'update_date_mean': -1.3792745683403569, 'report_date_mean': -1.3792745683403569, 'prod_limit_mean': 0.4983620733842888, 'new_balance_mean': 0.5395174549534726, 'highest_balance_mean': 1.1918982333447932}, {'id': 0.6311033038845512, 'fea_1': 1.1012601411532634, 'fea_2': -1.02562848255036, 'fea_3': 0.7999232200119571, 'fea_4': 0.004835169868255, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -0.0131282786815867, 'fea_8': 0.9366244353457758, 'fea_9': -0.3520297846853395, 'fea_10': -0.5265622771629388, 'fea_11': 0.740809615371274, 'OVD_t1_mean': 1.9080889448207128, 'OVD_t1_max': 1.5761032127019163, 'OVD_t2_mean': 1.962691476402652, 'OVD_t2_max': 1.863669262634988, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': 1.4389424065011351, 'pay_normal_max': 0.9568946399352508, 'prod_code_median': 0.5114972949866168, 'update_date_mean': -0.0672528185650725, 'report_date_mean': -0.0672528185650725, 'prod_limit_mean': -1.4100783324038126, 'new_balance_mean': -0.3076323152474232, 'highest_balance_mean': -0.4207166538207108}, {'id': 0.6360583130225528, 'fea_1': 1.1012601411532634, 'fea_2': 0.3307215008679215, 'fea_3': 0.7999232200119571, 'fea_4': -0.5782042618304059, 'fea_5': 0.2969011435096554, 'fea_6': 0.1323902907633703, 'fea_7': -0.0131282786815867, 'fea_8': -0.2785838896599469, 'fea_9': 1.0185622338373752, 'fea_10': 1.329736819787679, 'fea_11': 0.8138127420413124, 'OVD_t1_mean': 1.076115499686606, 'OVD_t1_max': 0.8753213294496587, 'OVD_t2_mean': -0.4884914534377256, 'OVD_t2_max': -0.4984190282472489, 'OVD_t3_mean': -0.381706742730764, 'OVD_t3_max': -0.3954451925699495, 'pay_normal_mean': -0.6953983139837454, 'pay_normal_max': 0.8053610226981562, 'prod_code_median': 0.5114972949866168, 'update_date_mean': 0.4501502234513199, 'report_date_mean': 0.4501502234513199, 'prod_limit_mean': -2.1836951546760632, 'new_balance_mean': -0.1963711679975588, 'highest_balance_mean': -0.4125831808049976}, {'id': 0.626281304567862, 'fea_1': -0.3493341442095938, 'fea_2': 1.7264389235922109, 'fea_3': 0.7999232200119571, 'fea_4': -0.3588639050383689, 'fea_5': 0.2969011435096554, 'fea_6': 1.472568321829104, 'fea_7': -0.0131282786815867, 'fea_8': 1.5024325690062814, 'fea_9': 1.0185622338373752, 'fea_10': 0.650247774085827, 'fea_11': -1.2956658750858463, 'OVD_t1_mean': 0.562836911752621, 'OVD_t1_max': 1.4792136444357704, 'OVD_t2_mean': 0.7145710195638568, 'OVD_t2_max': 1.863669262634988, 'OVD_t3_mean': 1.9117068541378

In [3]:
import mlflow
mlflow.set_tracking_uri("http://localhost:5000")

In [6]:
import logging
logging.basicConfig(level=logging.DEBUG)
import mlflow

mlflow.set_tracking_uri("http://localhost:5000")

with mlflow.start_run():
    mlflow.log_param("test_param", 123)

DEBUG:urllib3.connectionpool:Resetting dropped connection: localhost
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /api/2.0/mlflow/runs/create HTTP/1.1" 200 900
DEBUG:urllib3.connectionpool:Resetting dropped connection: localhost
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /api/2.0/mlflow/runs/log-parameter HTTP/1.1" 200 2
DEBUG:urllib3.connectionpool:Resetting dropped connection: localhost
DEBUG:urllib3.connectionpool:http://localhost:5000 "GET /api/2.0/mlflow/runs/get?run_uuid=72ccb0287deb41328766ecdb4f54b5c2&run_id=72ccb0287deb41328766ecdb4f54b5c2 HTTP/1.1" 200 1021
DEBUG:urllib3.connectionpool:Resetting dropped connection: localhost
DEBUG:urllib3.connectionpool:http://localhost:5000 "POST /api/2.0/mlflow/runs/update HTTP/1.1" 200 424

🏃 View run luminous-perch-271 at: http://localhost:5000/#/experiments/0/runs/72ccb0287deb41328766ecdb4f54b5c2
🧪 View experiment at: http://localhost:5000/#/experiments/0